SET check_function_bodies = false;
SET client_min_messages = warning;

--DROP SCHEMA agencia;


DROP TABLE COMODOS CASCADE;

DROP TABLE MOBILIAS CASCADE;

DROP TABLE COMMOB CASCADE;

DROP TABLE CONTRATOS CASCADE;

DROP TABLE AMBIENTES CASCADE;

DROP TABLE ITENSVENDA CASCADE;

DROP TABLE TIPOCOMMOB CASCADE;